[package]
name = "provider-core"
version = "0.1.0"
edition = "2024"

[dependencies]
secrecy = "0.10.3"
harness-core = { path = "../harness-core" }
async-trait = "0.1.89"
anyhow = "1.0.102"
tokio-util = "0.7.18"
tokio = { version = "1.52.3", features = ["sync"] }
futures-core = "0.3.32"
serde = "1.0.228"
